version: "2"
services:
  node:
    build: .
    user: "node"
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ./app/:/usr/app/
      - /usr/app/node_modules
    command: "npm start"
